# Generated by Django 5.1.2 on 2024-10-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('priority', models.CharField(choices=[('MEDIUM', 'medium'), ('HIGH', 'high'), ('LOW', 'low')], max_length=10)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
