# Generated by Django 5.1.2 on 2024-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('MEDIUM', 'medium')], max_length=10),
        ),
    ]
